module.exports = {
	INVALID_USER: "INVALID_USER",
	DISABLED_USER: "DISABLED_USER",
	WRONG_PASSWORD: "WRONG_PASSWORD",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	NOT_FOUND: "DATA_NOT_FOUND",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	CREATED_SUCCESSFULLY: "CREATED_SUCCESSFULLY",
	UPDATED_SUCCESSFULLY: "UPDATED_SUCCESSFULLY",
	DELETED_SUCCESSFULLY: "DELETED_SUCCESSFULLY",
	READING_CSV_SUCCESS: "READING_CSV_IMPORT",
	TOKEN_EXPIRED: "Token Expired",
	TOKEN_AUTHENTICATION_FAILED: "Failed to authenticate Token",
	NO_TOKEN: "No token provided"
};
